### ISSUE TITLE
fadvisor use  servicemonitors to configure  prometheus scrape 

### ISSUE THREAD

**Issue by tommylxf** [gocrane/fadvisor#18]
k8s version: 1.21.10
fadvisor version: v0.3.0

**Comment by zhuw0312** [comment]
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crane-metrics
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  namespaceSelector:
    matchNames:
    - crane-system
  selector:
    matchLabels:
      app.kubernetes.io/name: fadvisor
  endpoints:
  - port: http
```
